# Generated by Django 5.0.6 on 2024-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=64)),
                ('learning', models.ManyToManyField(blank=True, related_name='disc', to='schedule.daysoftheweek')),
            ],
        ),
    ]
