# Generated by Django 5.0.6 on 2024-06-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_vykladach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
                ('learn2', models.ManyToManyField(blank=True, related_name='group', to='schedule.daysoftheweek')),
            ],
        ),
    ]
